# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 14:29
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=3100)),
            ],
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=account.models.generate_new_link, max_length=120, unique=True)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(default=account.models.default_expire_date)),
                ('activation_count', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='invite_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.InviteLink'),
        ),
    ]
